
email: contact@bessapromotion.com
description: > # this means to ignore newlines until "baseurl:"
google_maps_javascript_api_key: "AIzaSyBBaTWG9lPQ4zidxNDHGeBKMFfpfxZryRo"
sass:
    style: compressed
exclude:
   ['README.markdown', 'Gemfile.lock', 'Gemfile', 'gulpfile','README','screenshot','node_modules','CODE_OF_CONDUCT','LICENCE','package.json',package-lock.json]
plugins:
  ['jekyll-redirect-from','jekyll-seo-tag','octopress-autoprefixer','jekyll-sitemap']
lang: fr
author: Bessa Promotion
social:
  name: Bessa Promotion
  links:
    - https://www.facebook.com/PromotionBessa/
    - https://www.linkedin.com/company/bessapromotion
    - https://www.pinterest.com/bessapromotion0262/
    - https://twitter.com/bessapromotion
