backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "img/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "singlepost"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Seo", name: "description", widget: "string"}
      - {label: "picture", name: "picture", widget: "image"}
      - {label: "thumbnail", name: "thumb", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "comments", name: "comments", widget: "boolean", default: true}
